isudo: required

services:
- docker

script:
  - docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE} ${DOCKER_BUILDDIR}
  - docker push ${DOCKER_REPO}/${DOCKER_IMAGE}

